name: Build golang application

on:
  pull_requests:
    branches:
      - develop
      - master
  push:
    branches:
      - master
      - develop

jobs: 
  build:
    name: Build the golang repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use golang ${{matrix.go-version}}
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go version    