name: Build golang application

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - master
      - develop

jobs: 
  build:
    name: Build the golang repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use golang ${{matrix.go-version}}
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go version    


      - name: Build the repository
        run: |
          go build server.go

  deploy:
    name: Deploy the repository to google app engine
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependency for google cloud SDK
        run: |
          sudo apt-get install google-cloud-sdk-app-engine-go

      - name: Make env variable file
        run: |
          echo "DB_HOST=${{secrets.DB_HOST}}
          DB_PORT=${{secrets.DB_PORT}}
          DB_NAME=${{secrets.DB_NAME}}
          DB_USER=${{secrets.DB_USERNAME}}
          DB_PASS=${{secrets.DB_PASSWORD}}
          DB_TYPE=${{secrets.DB_TYPE}}
          REDIS_HOST=${{secrets.REDIS_HOST}}
          ENVIRONMENT=${{secrets.ENVIRONMENT}}
          "> .env

      - name: Use golang ${{matrix.go-version}}
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go version


      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Deploy to Google App engine
        run: |
          gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud app deploy app.yaml -q --project ${{secrets.PROJECT_ID}}