name: Build and deploy to staging

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Buid the golang repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use golang ${{matrix.go-version}}
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go version    


      - name: Build the repository
        run: |
          go build server.go